//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TB()
        {
            this.PUR_TB = new HashSet<PUR_TB>();
        }
    
        public int ID { get; set; }
        public string CAT_Name { get; set; }
        public byte[] CAT_Cover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUR_TB> PUR_TB { get; set; }
    }
}
