//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_TB
    {
        public int ID { get; set; }
        public string CUST_Name { get; set; }
        public string CUST_Phone { get; set; }
        public string CUST_Email { get; set; }
        public byte[] CUST_Image { get; set; }
    }
}
