//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMP_DBEntities : DbContext
    {
        public SMP_DBEntities()
            : base("name=SMP_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_TB> CAT_TB { get; set; }
        public virtual DbSet<SUPP_TB> SUPP_TB { get; set; }
        public virtual DbSet<PUR_TB> PUR_TB { get; set; }
        public virtual DbSet<CUST_TB> CUST_TB { get; set; }
        public virtual DbSet<SELL_TB> SELL_TB { get; set; }
        public virtual DbSet<USER_TB> USER_TB { get; set; }
    }
}
