//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPP_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPP_TB()
        {
            this.PUR_TB = new HashSet<PUR_TB>();
        }
    
        public int ID { get; set; }
        public string SUPP_Name { get; set; }
        public string SUPP_Phone { get; set; }
        public string SUPP_Email { get; set; }
        public byte[] SUPP_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUR_TB> PUR_TB { get; set; }
    }
}
